steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/Linty-Services/CD-Demo"]
    env: ["PROJECT_ROOT=github.com/Linty-Services/CD-Demo"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/refined-gravity-235213/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/refined-gravity-235213/gcp-cd-codelab:$REVISION_ID"
